version: "3.8"

services:
  # frontend:
  #   container_name: frontend
  #   build:
  #     context: ./frontend/
  #     dockerfile: Dockerfile
  #   volumes:
  #     - ./frontend/src:/code/src/
  #     - ./frontend/public:/code/public/
  #   ports:
  #     - 5173:5173

  # backend:
  #   container_name: backend
  #   build:
  #     context: ./backend/
  #     dockerfile: Dockerfile
  #   volumes:
  #     - ./backend/:/code/
  #   ports:
  #     - 8000:8000

  mailserver:
    container_name: mailserver
    image: schickling/mailcatcher
    ports:
      - 1080:1080
      - 1025:1025
