version: "3.8"

services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    volumes:
      - ./frontend/src:/code/src/
      - ./frontend/public:/code/public/

  backend:
    container_name: backend
    build:
      context: ./backend/
      dockerfile: Dockerfile
    volumes:
      - ./backend/backend:/code/backend/
    ports:
      - 8000:8000

  mail:
    container_name: mail
    image: schickling/mailcatcher
    ports:
      - 1080:1080
      - 1025:1025
